### ISSUE TITLE
General Editing

### ISSUE THREAD

**Issue by mdhaber** [MrShoenel/metrics-as-scores#11]
- [x] The adjacent sentences that describe what ANOVA does should probably be combined
![image](https://user-images.githubusercontent.com/6570539/228148392-1ce73378-58bd-4c70-af20-16b035838a27.png)

- [x] Capitalization after a colon is not appropriate unless the colon introduces a complete sentence. Here, the colon introduces a phrase / incomplete sentence. 
![image](https://user-images.githubusercontent.com/6570539/228148613-2c79e308-cc36-4573-9732-1da9171e3f12.png)
 
- [x] Does "feature" refer to the quantity being measured or the numerical values of the measurement? (I would have thought the former, but then I would ask whether it is really the quantity being transformed; I would think it is the numerical values.) **Also**, although (unfortunately) "sample" is used to refer to both a single measurement and a collection of measurements, I've never seen "observation" to be used to refer to a collection of measurements. Consider whether "sample" is more appropriate than "observation" here.
![image](https://user-images.githubusercontent.com/6570539/228149372-74ca4573-272d-40bf-aa77-bfebc481a161.png)

- [x] From a certain perspective, a "unit change" of score would result in a value beyond the [0-1] range. Consider "fixed increment" , "given increment", or similar to avoid misunderstanding.
![image](https://user-images.githubusercontent.com/6570539/228149903-c4d2dff1-dc47-4164-9aa6-2ab7fb7c14e9.png)

- [x] Is the genetic algorithm here not Pymoo? If so, we need to consider whether the software that implements the genetic algorithm (and all the tests, distributions, etc.) should be cited. We should check with the editor as to whether it is appropriate for me to suggest this since I am biased, but it would be surprising to me if it is appropriate to cite Pymoo and not the other software.
![image](https://user-images.githubusercontent.com/6570539/228150314-c551654e-7d83-46a9-b612-24ef69e7d12e.png)

- [x] Typo in "of"
![image](https://user-images.githubusercontent.com/6570539/228154193-c6ab3bbd-aad7-4a8e-adaa-89c4154909e1.png)

- [x] Please research the use of "suspension hyphenation" to determine whether it is appropriate in these situations.
![image](https://user-images.githubusercontent.com/6570539/228156159-0728aa43-fdbe-4e2c-8b9d-e3ea0e178798.png)
![image](https://user-images.githubusercontent.com/6570539/228154753-8f4f6f2a-28cc-4d30-9790-72d5d7c940bd.png)
![image](https://user-images.githubusercontent.com/6570539/228154823-35fbccde-d6ca-42de-8a5d-1172e3b67a58.png)

**Comment by MrShoenel** [comment]
I have fixed all these in a number of smaller commits (e.g., 77b4e7c, 0397680, 8b23585, 241d851, 1a1eede, 704452a, 5646633, 0a74c97).

About your 3rd point: We changed "feature" to "quantity" and "observation" to "sample" as we think it makes the most sense.

About the 5th point: Pymoo does not explicitly disclose which algorithm is used, nor does it add a reference. The authors of Pymoo are also the authors of NSGA-II and other genetic algorithms, so I suppose they use one of their own. Because of this circumstance, I would keep the exact same reference.

**Comment by mdhaber** [comment]
> About the 5th point: Pymoo does not explicitly disclose which algorithm is used, nor does it add a reference. The authors of Pymoo are also the authors of NSGA-II and other genetic algorithms, so I suppose they use one of their own. Because of this circumstance, I would keep the exact same reference.

The reference for Pymoo is fine. But it says "genetic algorithm and Pymoo", suggesting that the "genetic algorithm" is not part of Pymoo. There is no reference for the "genetic algorithm". If you mean "genetic algorithm in Pymoo", then no additional citation is needed, but the wording needs to be adjusted.

**Comment by mdhaber** [comment]
![image](https://user-images.githubusercontent.com/6570539/234401554-cb428388-bb3a-4fb5-8036-69927d12593b.png)

"mathematically sound"

**Comment by mdhaber** [comment]
![image](https://user-images.githubusercontent.com/6570539/234401835-800126f0-1f77-4f0c-b253-2f16683da45f.png)

"are" or "may be"

**Comment by mdhaber** [comment]
![image](https://user-images.githubusercontent.com/6570539/234401960-1145264a-2561-423d-9c22-149c1bcbffab.png)

I don't think you want the infinitive form "to transform" here. Consider
> Metrics As Scores supports the transformation of...

or just

> Metrics As Scores transforms...

**Comment by MrShoenel** [comment]
All were adjusted as per your suggestions (agreed!) in ee6907c.

**Comment by MrShoenel** [comment]
All were adjusted as per your suggestions (agreed!) in ee6907c.
