### ISSUE TITLE
API Documentation

### ISSUE THREAD

**Issue by mdhaber** [MrShoenel/metrics-as-scores#2]
One of the items in the JOSS review criteria #1 is:

> **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)? 

I don't see any rendered API documentation or even docstrings in the code.
Please add detailed documentation to satisfy this criterion (or point me to the documentation I am missing). Thanks!

**Comment by MrShoenel** [comment]
The full API documentation is now available at <https://mrshoenel.github.io/metrics-as-scores/>.
I will update the readme tomorrow and also add another reference there.

**Comment by MrShoenel** [comment]
The documentation is now complete.

**Comment by mdhaber** [comment]
It looks like there is API documentation. I have a few questions/comments about it:

![image](https://user-images.githubusercontent.com/6570539/220185199-c187db51-913b-4878-8cf2-53d46b868637.png)

What is the difference between "metrics_as_scores" and "metrics_as_scores package" here?

Could you describe the subpackages as you describe each function?

"Module Contents" are blank.
![image](https://user-images.githubusercontent.com/6570539/220185362-ebd2d545-9c76-4020-8717-c97f62ba93f4.png)

Is a user ever intended to use the API directly (as with SciPy/matplotlib/scikit-learn), or do they only use the web app / TUI (and the API is just for the developer)?

**Comment by MrShoenel** [comment]
The difference between "metrics_as_scores" and "metrics_as_scores package" is explained by Sphinx documenting Metrics As Scores on application level ("metrics_as_scores"), and then showing its (currently) only package (which has the same name).

While adding all missing (sub-)package- and module-level documentation (please see <https://mrshoenel.github.io/metrics-as-scores/index.html>) I have indicated that there might be additional top-level packages in the future. Therefore, I would like to keep the documentation the way it is today.

The documentation is primarily intended for developers, as the average user will only interact with the text-based user interface (i.e., no interactions with the code).
