### ISSUE TITLE
Citations/References

### ISSUE THREAD

**Issue by mdhaber** [MrShoenel/metrics-as-scores#8]
One of the items in the JOSS review criteria #8 is:

> **References**: Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax](https://pandoc.org/MANUAL.html#extension-citations)?

Most of this is satisfied, but there are a few places that are questionable - mostly the citations that are included within parentheses already.

For example:
![image](https://user-images.githubusercontent.com/6570539/228142118-23ac52e5-5469-4677-95c2-0cc6df4d4b02.png)

should probably not be an "author-in-text citation".

I'm not sure, but it looks like you want to do this by adding "ANOVA; " as a "prefix" to the citation:
![image](https://user-images.githubusercontent.com/6570539/228141917-ca71b655-f38f-410c-9303-2b1ad21713d6.png)

rather than explicitly adding parentheses.

Here are some other cases that are questionable.
![image](https://user-images.githubusercontent.com/6570539/228142325-003adb52-3bfa-4c8e-87e9-0929dfd9d216.png)
![image](https://user-images.githubusercontent.com/6570539/228142415-121707fa-9554-450c-8df3-cdd7e2f5e101.png)
![image](https://user-images.githubusercontent.com/6570539/228142468-ac8675be-5290-48e0-b875-a0adb96296f5.png)

Please do your best to satisfy the criterion, and if you're not sure what to do, we'll have to ask the editor.

**Comment by mdhaber** [comment]
Also, please manually review all references and format as needed. For instance, sometimes capitalization of proper nouns (e.g. September, Timisoara, Romania, Cramér, von Mises) needs to be forced.

![image](https://user-images.githubusercontent.com/6570539/228145808-befa5908-94ea-46be-b9d4-82eca82a6b08.png)

**Comment by MrShoenel** [comment]
All of these are resolved now (e.g., 77b4e7c, 1a1eede), so I think it can be closed.

**Comment by mdhaber** [comment]
Same as in top post
![image](https://user-images.githubusercontent.com/6570539/233659480-1fb2321a-e873-4300-bb31-5b0a94a9f2f5.png)

Also, there is a period missing after the "g" in "e.g.".

**Comment by mdhaber** [comment]
I don't think this reference is complete:
![image](https://user-images.githubusercontent.com/6570539/233659951-52dff6cb-0c48-40d5-a515-5c1bf268355d.png)

"Student's" should be capitalized:
![image](https://user-images.githubusercontent.com/6570539/233660112-707f8424-741b-461b-8d95-9ab5b66b68d2.png)

There are a lot of other capitalization and abbreviation inconsistencies, but I will let the editors assess those.

**Comment by MrShoenel** [comment]
Good catches, I did correct all of these now ;)
