### ISSUE TITLE
State of the Field

### ISSUE THREAD

**Issue by mdhaber** [MrShoenel/metrics-as-scores#9]
One of the items in the JOSS review criteria #1 is:

> **State of the field**: Do the authors describe how this software compares to other commonly-used packages?

I didn't find this information the first time I read the paper nor in a recent re-read. If this description is present, it may need to be emphasized; if it is not present, it needs to be added.

**Comment by MrShoenel** [comment]
I will make this clear soon!

**Comment by MrShoenel** [comment]
There is a new short section at the end of the paper for related work.
